name: Bump Minor Version

on:
    workflow_dispatch:

permissions:
    contents: write

jobs:
    bump-minor-version:
        name: Bump Minor Version
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ssh-key: ${{ secrets.ACTIONS }}

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install Poetry
              run: pip install poetry

            - name: Bump minor version and create tag
              run: |
                  set -e
                  CURRENT=$(poetry version --short)
                  poetry version minor
                  NEW=$(poetry version --short)

                  git add pyproject.toml
                  git config user.name "github-actions"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

                  git commit -m "ci: $CURRENT â†’ $NEW" || echo "No version change"
                  git push

                  TAG="v$NEW"
                  git tag -a "$TAG" -m "Release $TAG"
                  git push origin "$TAG"
